#!/bin/bash

function compose-list() {
    composeList=$(docker-compose ls --all --format json | jq -r '.[] | "\(.Name)|\(.ConfigFiles)|\(.Status)"')
    composeFiles=$(
        echo -e "PROJECT\tPATH\tSTATUS"
        find "$COMPOSE_PATH" -maxdepth 3 -type f -name "*compose.y*ml" | while read -r path; do
            composeElemetn=$(echo "$composeList" | grep -F "$path" | head -n 1)
            if [ -n "$composeElemetn" ]; then
                projectName=$(echo "$composeElemetn" | awk -F'|' '{print $1}')
                status=$(echo "$composeElemetn" | awk -F'|' '{print $3}')
            else
                projectName=$(basename "$(dirname "$path")")
                serviceCount=$(cat "$path" | yq e '.services | length')
                status="down($serviceCount)"
            fi
            echo -e "$projectName\t$path\t$status"
        done
    )
    composeFiles=$(echo "$composeFiles" | column -t -s $'\t')
    echo "$composeFiles" | sed "1d" | fzf \
        --reverse \
        --color="header:blue:bold,pointer:bright-blue:bold" \
        --header "$(echo "$composeFiles" | head -n 1)" \
        --preview-window down:70%:wrap:follow \
        --preview "compose-stats {1}" \
        --bind "enter:execute(compose-ps-bind {1} {2})"
}

function compose-stats() {
    export COMPOSE_PROJECT_NAME="$1"
    while true; do
        stats=$(docker-compose stats --all --no-stream)
        header=$(echo "$stats" | head -n 1)
        echo -e "\x1b[34;1m$header\x1b[0m"
        echo "$stats" | sed "1d"
        sleep $TIMEOUT
        clear
    done
}

function compose-ps-bind() {
    export COMPOSE_PROJECT_NAME="$1"
    export COMPOSE_FILE="$2"
    ps=$(compose-services)
    echo "$ps" | sed "1d" | fzf \
        --reverse \
        --color="header:blue:bold,pointer:bright-blue:bold" \
        --header "$(echo "$ps" | head -n 1)" \
        --preview-window down:70%:wrap:follow \
        --preview "compose-logs {1}" \
        --bind "enter:execute(custom-commands-list {1})+reload(compose-services | sed '1d')+transform-header(compose-services | head -n 1)"
}

function compose-services() {
    ps=$(docker-compose ps --all --format "$DOCKER_PS_FORMAT")
    serviceCount=$(echo "$ps" | wc -l)
    if [ "$serviceCount" -le 1 ]; then
        ps=$(
            {
                echo -e "SERVICE\tSTATUS"
                yq e '.services | keys | .[]' "$COMPOSE_FILE" | while read -r svc; do
                    echo -e "$svc\tdown"
                done
            } | column -t -s $'\t'
        )
    fi
    echo "$ps"
}

function compose-logs() {
    export COMPOSE_SERVICE_NAME="$1"
    while true; do
        docker logs "$COMPOSE_SERVICE_NAME" --timestamps --tail 100 2>&1 | tspin
        sleep $TIMEOUT
        clear
    done
}

function custom-commands-list() {
    export COMPOSE_SERVICE_NAME="$1"
    mapfile -t commands < <(yq e '.customCommands[].name' config.yml)
    commandsName=$(printf "%s\n" "${commands[@]}")
    echo "$commandsName" | fzf \
        --reverse \
        --preview-window up:30%:wrap:follow \
        --preview "compose-ps-preview" \
        --bind "enter:execute(custom-command-run '{}')"
}

function compose-ps-preview() {
    while true; do
        ps=$(compose-services)
        serviceCount=$(($(echo "$ps" | wc -l) - 1))
        upCount=0
        exitCount=0
        lines=()
        while read -r line; do
            sn=$(echo "$line" | awk '{print $1}')
            status=$(echo "$line" | awk '{print $2}')
            if [[ "$sn" == "$COMPOSE_SERVICE_NAME" ]]; then
                line="\x1b[34;1m▶\x1b[0m  $line"
            else
                line="   $line"
            fi
            case "$status" in
                Up*) ((upCount++)) ;;
                *)   ((exitCount++)) ;;
            esac
            lines+=("$line")
        done < <(echo "$ps" | sed "1d")
        header=$(echo "$ps" | head -n 1)
        if [ "$upCount" -eq "$serviceCount" ]; then
            icon="🟢"
        elif [ "$upCount" -ge 1 ]; then
            icon="🟡"
        else
            icon="🔴"
        fi
        header="📊 Status\n\n   \x1b[34;1m$header\x1b[0m"
        clear
        echo -e "$header"
        IFS=$'\n'
        echo -e "${lines[*]}"
        sleep $TIMEOUT
    done
}

function custom-command-run() {
    COMMAND_NAME="$*"
    command=$(yq e ".customCommands[] | select(.name == \"$COMMAND_NAME\") | .command" config.yml)
    attach=$(yq e ".customCommands[] | select(.name == \"$COMMAND_NAME\") | .attach" config.yml)
    eval "$command"
    if [ "$attach" == "true" ]; then
        read -r
    fi
}

export -f compose-list
export -f compose-stats
export -f compose-ps-bind
export -f compose-services
export -f compose-logs
export -f custom-commands-list
export -f compose-ps-preview
export -f custom-command-run

# export COMPOSE_PATH=${COMPOSE_PATH:-/docker}
export COMPOSE_PATH=${COMPOSE_PATH:-/home/lifailon/docker}
export TIMEOUT=${TIMEOUT:-2}

export DOCKER_PS_FORMAT="table {{.Service}}\t{{.Status}}\t{{.RunningFor}}\t{{.Image}}\t{{.Command}}\t{{.Ports}}"
export FZF_DEFAULT_OPTS="
--no-sort
--ansi
--wrap
--border
--list-border
--height=100%
--prompt='🔎 '
--pointer='▶ '
"

clear
if [ "$TTYD_MODE" == "true" ]; then
    TTYD_OPTIONS="-W -p ${TTYD_PORT:-3333}"
    if [ -n "${TTYD_USER}" ] && [ -n "${TTYD_PASS}" ]; then
        TTYD_OPTIONS+=" -c ${TTYD_USER}:${TTYD_PASS}"
    fi
    # exec ttyd $TTYD_OPTIONS bash -c compose-list
    ttyd $TTYD_OPTIONS bash -c compose-list
else
    # exec bash -c compose-list
    bash -c compose-list
fi
