#!/bin/bash

function compose-list() {
    projects=$(compose-find)
    echo "$projects" | sed "1d" | fzf \
        --reverse \
        --color="header:blue:bold,pointer:bright-blue:bold" \
        --header "$(echo "$composeFiles" | head -n 1)" \
        --preview-window down:70%:wrap:follow \
        --preview "compose-stats {1}" \
        --bind "enter:execute(compose-ps-bind {1} {2})+reload(compose-find | sed '1d')+transform-header(compose-find | head -n 1)"
}

function compose-find() {
    composeList=$(docker-compose ls --all --format json | jq -r '.[] | "\(.Name)|\(.ConfigFiles)|\(.Status)"')
    composeFiles=$(
        echo -e "PROJECT\tPATH\tSTATUS"
        find "$COMPOSE_PATH" -maxdepth "$COMPOSE_FIND_DEPTH" -type f -name "*compose.y*ml" | while read -r path; do
            composeElemetn=$(echo "$composeList" | grep -F "$path" | head -n 1)
            if [ -n "$composeElemetn" ]; then
                projectName=$(echo "$composeElemetn" | awk -F'|' '{print $1}')
                status=$(echo "$composeElemetn" | awk -F'|' '{print $3}')
            else
                projectName=$(basename "$(dirname "$path")")
                serviceCount=$(cat "$path" | yq e '.services | length')
                status="down($serviceCount)"
            fi
            echo -e "$projectName\t$path\t$status"
        done
    )
    echo "$composeFiles" | column -t -s $'\t'
}

function compose-stats() {
    export COMPOSE_PROJECT_NAME="$1"
    while true; do
        stats=$(docker-compose stats --all --no-stream)
        header=$(echo "$stats" | head -n 1)
        echo -e "\x1b[34;1m$header\x1b[0m"
        echo "$stats" | sed "1d"
        sleep $COMPOSE_STATUS_TIMEOUT
        clear
    done
}

function compose-ps-bind() {
    export COMPOSE_PROJECT_NAME="$1"
    export COMPOSE_FILE="$2"
    ps=$(compose-services)
    echo "$ps" | sed "1d" | fzf \
        --reverse \
        --color="header:blue:bold,pointer:bright-blue:bold" \
        --header "$(echo "$ps" | head -n 1)" \
        --preview-window down:70%:wrap:follow \
        --preview "compose-logs {1}" \
        --bind "enter:execute(custom-commands-list {1} {2})+reload(compose-services | sed '1d')+transform-header(compose-services | head -n 1)"
}

function compose-services() {
    ps=$(docker-compose ps --all --format "$DOCKER_PS_FORMAT")
    serviceCount=$(echo "$ps" | wc -l)
    if [ "$serviceCount" -le 1 ]; then
        ps=$(
            {
                echo -e "SERVICE\tIMAGE\tSTATE"
                services=$(yq e '.services | select(. != null) | keys | .[]' "$COMPOSE_FILE")
                if [[ -z "$services" ]]; then
                    echo -e "null\tnull\tdown"
                else
                    echo "$services" | while read -r svc; do
                        img=$(yq e ".services.$svc.image // \"null\"" "$COMPOSE_FILE")
                        echo -e "$svc\t$img\tdown"
                    done
                fi
            } | column -t -s $'\t'
        )
    fi
    lines=()
    header=true
    while read -r line; do
        if $header; then 
            header=false
            line=$(echo "$line" | sed "s/STATUS/   STATUS/")
            lines+=("$line")
            continue
        fi
        state=$(echo "$line" | awk '{print $3}')
        case "$state" in
            run*)  status="🟢" ;;
            exit*) status="🔴" ;;
            down*) status="🔴" ;;
            *)     status="🟡" ;;
        esac
        resetColor="\033[0m"
        line=$(echo "$line" | sed "s/$state/$status $state/")
        lines+=("$line")
    done < <(echo "$ps")
    IFS=$'\n'
    echo "${lines[*]}" | column -t -s $'\t'
}

function compose-logs() {
    export COMPOSE_SERVICE_NAME="$1"
    while true; do
        docker logs "$COMPOSE_SERVICE_NAME" --tail 100 2>&1 | tspin
        sleep $COMPOSE_STATUS_TIMEOUT
        clear
    done
}

function custom-commands-list() {
    export COMPOSE_SERVICE_NAME="$1"
    export COMPOSE_IMAGE_NAME="$2"
    mapfile -t commands < <(yq e '.customCommands[].name' config.yml)
    commandsName=$(printf "%s\n" "${commands[@]}")
    echo "$commandsName" | fzf \
        --reverse \
        --preview-window up:30%:wrap:follow \
        --preview "compose-ps-preview" \
        --bind "enter:execute(custom-command-run '{}')"
}

function compose-ps-preview() {
    while true; do
        ps=$(compose-services)
        header=$(echo "$ps" | head -n 1)
        header="📊 Status\n\n   \x1b[34;1m$header\x1b[0m"
        lines=()
        while read -r line; do
            serviceName=$(echo "$line" | awk '{print $1}')
            if [[ "$serviceName" == "$COMPOSE_SERVICE_NAME" ]]; then
                line="\x1b[34;1m▶\x1b[0m  $line"
            else
                line="   $line"
            fi
            lines+=("$line")
        done < <(echo "$ps" | sed "1d")
        clear
        echo -e "$header"
        IFS=$'\n'
        echo -e "${lines[*]}"
        sleep $COMPOSE_STATUS_TIMEOUT
    done
}

function custom-command-run() {
    COMMAND_NAME="$*"
    command=$(yq e ".customCommands[] | select(.name == \"$COMMAND_NAME\") | .command" config.yml)
    attach=$(yq e ".customCommands[] | select(.name == \"$COMMAND_NAME\") | .attach" config.yml)
    eval "$command"
    if [ "$attach" == "true" ]; then
        read -r
    fi
}

export -f compose-list
export -f compose-find
export -f compose-stats

export -f compose-ps-bind
export -f compose-services
export -f compose-logs

export -f custom-commands-list
export -f compose-ps-preview
export -f custom-command-run

# export COMPOSE_PATH=${COMPOSE_PATH:-/docker}
export COMPOSE_PATH=${COMPOSE_PATH:-/home/lifailon/docker}
export COMPOSE_FIND_DEPTH=${COMPOSE_FIND_DEPTH:-3}
export COMPOSE_STATUS_TIMEOUT=${COMPOSE_STATUS_TIMEOUT:-2}

export DOCKER_PS_FORMAT="table {{.Service}}\t{{.Image}}\t{{.State}}\t{{.Status}}\t{{.RunningFor}}\t{{.Command}}\t{{.Ports}}"
export FZF_DEFAULT_OPTS="--no-sort --ansi --wrap --border --list-border --height=100% --prompt='🔎 ' --pointer='▶ '"

clear
if [ "$TTYD_MODE" == "true" ]; then
    TTYD_OPTIONS="-W -p ${TTYD_PORT:-3333}"
    if [ -n "${TTYD_USER}" ] && [ -n "${TTYD_PASS}" ]; then
        TTYD_OPTIONS+=" -c ${TTYD_USER}:${TTYD_PASS}"
    fi
    # exec ttyd $TTYD_OPTIONS bash -c compose-list
    ttyd $TTYD_OPTIONS bash -c compose-list
else
    # exec bash -c compose-list
    bash -c compose-list
fi